// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDynt0WqkqUS5277yM-KgAnX0CK11O1J7w',
    appId: '1:417838890060:web:47f32cd1c91fc9e8c708e9',
    messagingSenderId: '417838890060',
    projectId: 'robogpt-1bc91',
    authDomain: 'robogpt-1bc91.firebaseapp.com',
    storageBucket: 'robogpt-1bc91.firebasestorage.app',
    measurementId: 'G-F8XKTMEBX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJT30h64vCn6kqCCxwhNbwg00Nfe8j1M0',
    appId: '1:417838890060:android:db832e90fa0678cbc708e9',
    messagingSenderId: '417838890060',
    projectId: 'robogpt-1bc91',
    storageBucket: 'robogpt-1bc91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3TeEm8e5iA_mQas20NVcRofM1HS06gJQ',
    appId: '1:417838890060:ios:84ab3d7d7ada346cc708e9',
    messagingSenderId: '417838890060',
    projectId: 'robogpt-1bc91',
    storageBucket: 'robogpt-1bc91.firebasestorage.app',
    iosBundleId: 'com.example.robogpt',
  );

}